// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get all audio input devices on the system.
Future<List<AudioInputDevice>> getInputDevices() =>
    RustLib.instance.api.crateApiAudioDevicesGetInputDevices();

Future<AudioInputDevice> getDefaultInputDevice() =>
    RustLib.instance.api.crateApiAudioDevicesGetDefaultInputDevice();

/// Get all audio output devices on the system.
Future<List<AudioOuputDevice>> getOutputDevices() =>
    RustLib.instance.api.crateApiAudioDevicesGetOutputDevices();

Future<AudioOuputDevice> getDefaultOutputDevice() =>
    RustLib.instance.api.crateApiAudioDevicesGetDefaultOutputDevice();

class AudioInputDevice {
  final String name;
  final bool systemDefault;

  const AudioInputDevice({
    required this.name,
    required this.systemDefault,
  });

  @override
  int get hashCode => name.hashCode ^ systemDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioInputDevice &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          systemDefault == other.systemDefault;
}

class AudioOuputDevice {
  final String name;
  final bool systemDefault;

  const AudioOuputDevice({
    required this.name,
    required this.systemDefault,
  });

  @override
  int get hashCode => name.hashCode ^ systemDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioOuputDevice &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          systemDefault == other.systemDefault;
}
