// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<AudioInputDevice>> getInputDevices() =>
    RustLib.instance.api.crateApiAudioDevicesGetInputDevices();

class AudioInputDevice {
  final String name;
  final bool systemDefault;
  final int rating;

  const AudioInputDevice({
    required this.name,
    required this.systemDefault,
    required this.rating,
  });

  @override
  int get hashCode => name.hashCode ^ systemDefault.hashCode ^ rating.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioInputDevice &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          systemDefault == other.systemDefault &&
          rating == other.rating;
}
