// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<LightwireEngine> createLightwireEngine() =>
    RustLib.instance.api.crateApiEngineCreateLightwireEngine();

Stream<(Uint8List, bool)> startPacketStream(
        {required LightwireEngine engine}) =>
    RustLib.instance.api.crateApiEngineStartPacketStream(engine: engine);

Future<void> setVoiceEnabled(
        {required LightwireEngine engine, required bool enabled}) =>
    RustLib.instance.api
        .crateApiEngineSetVoiceEnabled(engine: engine, enabled: enabled);

class LightwireEngine {
  final int id;

  const LightwireEngine({
    required this.id,
  });

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LightwireEngine &&
          runtimeType == other.runtimeType &&
          id == other.id;
}
